PORTNAME=	itpp
PORTVERSION=	4.3.1
PORTREVISION=	8
CATEGORIES=	ftp
MASTER_SITES=	SF

MAINTAINER=	chip-set@mail.ru
COMMENT=	Upload files or directories to FTP server with resume support
WWW=		https://itpp.sourceforge.net/

LICENSE=	GPLv2
LICENSE_FILE=	${WRKSRC}/COPYING

USES=		tar:bz2 cmake:noninja

GNU_CONFIGURE=	yes

MAKE_JOBS_UNSAFE=yes



.include <bsd.port.pre.mk>



post-install:


	

.include <bsd.port.post.mk>
