PORTNAME=       apk-editor-studio
DISTVERSION=    1.7.2
CATEGORIES=     misc

MAINTAINER=     your@email.com
COMMENT=        Powerful yet easy to use APK editor for PC and Mac.
WWW=            

LICENSE=        MIT
LICENSE_FILE=   ${WRKSRC}/LICENSE


USES=		cmake:noninja
USE_GITHUB=     yes
GH_ACCOUNT=     kefir500
GH_TAGNAME=     v${DISTVERSION}         


.include <bsd.port.mk>