PORTNAME=	xboxdrv
DISTVERSION=	0.0.1-1
DISTVERSIONSUFFIX=	-g0705fa1
CATEGORIES=	sysutils

USE_GITHUB=	yes
GH_ACCOUNT=	xboxdrv

WWW=		https://github.com/xboxdrv/xboxdrv

USES=		cmake:noninja


post-install:

.include <bsd.port.mk>
