PORTNAME=       moonplayer
DISTVERSION=    v4.3
CATEGORIES=     multimedia

MAINTAINER=     ports@FreeBSD.org
COMMENT=        MoonPlayer is an interesting player that lets you to enjoy videos.
WWW=            https://coslyk.github.io/moonplayer.html

BUILD_DEPENDS=  

USES=           cmake
USE_GITHUB=     yes
GH_ACCOUNT=     coslyk
GH_TUPLE+=      coslyk:danmaku2ass_cpp:00cbe11bdd81529b29b28907bd00b702363db45b:coslyk/3rdparty/danmaku2ass_cpp \
		selsta:hlsdl:883acbdb59ada7739f3ae75207bb74bac1994f75:selsta/3rdparty/hlsdl


post-patch:

.include <bsd.port.mk>