PORTNAME=	obs-composite-blur
DISTVERSION=	v1.1.0
DISTVERSIONSUFFIX=	-g033aaf2
CATEGORIES=	multimedia

USE_GITHUB=	yes
GH_ACCOUNT=	FiniteSingularity
GH_PROJECT=     obs-composite-blur

USES=		cmake:noninja

CMAKE_ARGS=	-DOBS_STUDIO_DIR=${LOCALBASE}/lib

 
.include <bsd.port.mk>