PORTNAME=	byedpi
DISTVERSION=	v0.17.3-1
DISTVERSIONSUFFIX=	-g9938d74
CATEGORIES=	net

USE_GITHUB=	yes
GH_ACCOUNT=	hufrea

WWW=	      	https://github.com/hufrea/byedpi

do-install:
		cp ${WRKSRC}/ciadpi                    ${STAGEDIR}${PREFIX}/bin 

.include <bsd.port.mk>
